from conda_env_toolkit import CondaManager

conda = CondaManager()

# 最终完整测试
test_packages = [
    # 用户原始问题
    'gettext', 'libasprintf', 'libasprintf-devel', 'libblas', 'libcblas',
    'libfreetype', 'libfreetype6', 'libgcc', 'libgettextpo', 'libgettextpo-devel',
    'libgomp', 'libintl', 'libintl-devel', 'liblapack', 'libsqlite',
    'libwinpthread', 'libxcb',
    # Debian/Ubuntu 风格
    'libkeyutils1', 'libnspr4', 'libnss3', 'libnssutil3', 'libplds4', 'libplc4',
    'libreadline8', 'libwayland-client0', 'libwayland-cursor0', 'libwayland-egl1',
    'libxkbcommon0', 'libxkbcommon-x11-0', 'libxshmfence1', 'libxss1', 'libxt6',
    'libxv1', 'libxxf86vm1', 'libzstd1',
    # 各种 lib 包
    'libaec', 'libb2', 'libcups', 'libdap', 'libdapclient', 'libdapserver',
    'libdb', 'libdc1394', 'libde265', 'libdrm', 'libedit', 'libexif',
    'libgc', 'libgd', 'libgfortran-ng', 'libgpg-error', 'libgphoto2',
    'libgs', 'libgudev', 'libheif', 'libhwy', 'libice', 'libidn11',
    'libiec61883', 'libigdgmm', 'libjpeg-turbo', 'libjxl', 'libkml',
    'liblensfun', 'liblerc', 'libllvm14', 'liblmdb', 'liblockfile',
    'libltdl', 'libmad', 'libmd', 'libmfx', 'libmodplug', 'libmpcdec',
    'libmpdec', 'libmpeg2', 'libmpg123', 'libmtdev', 'libnghttp2-14',
    'libnorm', 'libnotify', 'libnsl2', 'libnuma1', 'libodbc', 'libodbccr',
    'libodbcinst', 'libogg0', 'libopenal', 'libopengl0', 'libopenmpt',
    'libopus0', 'liborc-0.4-0', 'libosmesa6', 'libp11-kit0', 'libpaper1',
    'libpciaccess0', 'libpgm', 'libplacebo', 'libpoppler', 'libpq-dev',
    'libproxy', 'libpsl5', 'libpthread-stubs0', 'libpython3.10',
    'libqhull', 'libqpdf', 'libqt5core5a', 'librsvg2-2', 'librsvg2-common',
    'librttopo', 'librubberband2', 'libsamplerate0', 'libsctp1',
    'libsdl2-image', 'libsdl2-mixer', 'libsdl2-ttf', 'libserd', 'libsord',
    'libsratom', 'libsrt1.5', 'libssh-4', 'libsvtav1enc1', 'libsz2',
    'libtbb', 'libtbbmalloc2', 'libtdb1', 'libtevent0', 'libthai0',
    'libtiffxx5', 'libtinyxml2', 'libtirpc3', 'libtool-bin', 'libtre5',
    'libtwolame0', 'libudfread0', 'liburiparser1', 'libv4l-0',
    'libv4lconvert0', 'libva2', 'libva-drm2', 'libva-x11-2', 'libvdpau1',
    'libvidstab1.1', 'libvisual', 'libvncserver1', 'libvorbis0a',
    'libvorbisenc2', 'libvorbisfile3', 'libvpx7', 'libvulkan1', 'libwacom2',
    'libwacom-common', 'libwayland-server0', 'libwebp7', 'libwebpmux3',
    'libwildmidi2', 'libwrap0', 'libx265-199', 'libxcb-keysyms1',
    'libxcb-randr0', 'libxcb-shape0', 'libxcb-xfixes0', 'libxcb-xinerama0',
    'libxcb-xkb1', 'libxkbfile1', 'libxmu6', 'libxmuu1', 'libxpm4',
    'libxres1', 'libxvmc1', 'libxxhash0', 'libz3-4', 'libzimg2',
    'libzvbi0', 'libzvbi-common',
    # 其他变体
    'libbz2-1.0', 'libdb5.3', 'libexpat1', 'libgc1c2', 'libgdbm6',
    'libgdbm-compat4', 'libgpm2', 'libgssglue1', 'libicu70', 'libidn12',
    'liblcms2-2', 'liblzma5', 'libmagic-mgc', 'libmpdec3', 'libmpfr6',
    'libncurses6', 'libncursesw6', 'libnpth0', 'libpopt0', 'libproc2-0',
    'libsasl2-modules', 'libtinfo6', 'libuchardet0', 'libx11-data',
    'libxcb-util1', 'libxcb-util-keysyms1', 'libxcb-util-renderutil0',
    'libxcb-util-wm0', 'libxcb-xinput0', 'libxmlsec1', 'libxmlsec1-openssl',
    'libxslt1.1', 'libxxf86dga1',
    # 更多边缘库
    'libaio', 'libao', 'libapr', 'libaprutil', 'libart',
    'libasound', 'libasyncns', 'libatasmart', 'libavc1394',
    'libbind', 'libbinutils', 'libbio', 'libbison',
    'libblas3', 'libblkid1', 'libbluetooth', 'libbluray',
    'libbonobo', 'libbonoboui', 'libboot', 'libbsd',
    'libc6', 'libcaca', 'libcairo-gobject',
    'libcanberra', 'libcddb', 'libcdio',
    'libcdparanoia', 'libcfg', 'libcgraph', 'libchromaprint',
    'libck', 'libclutter', 'libcmis', 'libcmp',
    'libcolord', 'libcommon', 'libcompiz',
    'libconfig', 'libconfuse', 'libcroco', 'libcrystalhd',
    'libcups2', 'libcurl3', 'libcurl4', 'libcwidget',
    'libdaemon', 'libdatrie', 'libdb5.3++',
    'libdbus-1', 'libdbusmenu', 'libdc1394-22', 'libdca',
    'libdconf', 'libde265-0', 'libdevmapper', 'libdjvulibre',
    'libdlrestrictions', 'libdmapsharing', 'libdmx', 'libdns',
    'libdotconf', 'libdouble-conversion', 'libdpkg', 'libdrm2',
    'libdv', 'libdvbpsi', 'libdvdnav', 'libdvdread',
    'libe-book', 'libebackend', 'libebook', 'libecal',
    'libedata', 'libedataserver', 'libedit2', 'libeeze',
    'libefivar', 'libegl1', 'libelf1', 'libenca',
    'libenchant', 'libeot', 'libepoxy', 'libeps',
    'liberror', 'libesd', 'libespeak', 'libetonyek',
    'libev4', 'libevas', 'libevdev', 'libevent-2.1',
    'libexempi', 'libexif12', 'libexo', 'libexpat1-dev',
    'libexttextcat', 'libfaad', 'libfakekey', 'libfam',
    'libfbclient2', 'libfcgi', 'libfdisk', 'libffi6',
    'libfftw3', 'libfido2', 'libfile', 'libflac8',
    'libflite', 'libfluidsynth', 'libfm', 'libfontenc',
    'libfprint', 'libfreehand', 'libfreerdp', 'libfribidi0',
    'libfs', 'libfuse2', 'libfwupd', 'libgail',
    'libgarcon', 'libgbm', 'libgcab', 'libgcc1',
    'libgck', 'libgconf', 'libgcr', 'libgcroots',
    'libgd3', 'libgdal20', 'libgdata', 'libgdbm3',
    'libgdk-pixbuf', 'libgdraw', 'libgee', 'libgeoclue',
    'libgeocode', 'libgexiv2', 'libgfortran3', 'libgif7',
    'libgirepository', 'libglade', 'libglapi', 'libgles2',
    'libglib2.0', 'libglobus', 'libglpk', 'libglu1',
    'libgme', 'libgmime', 'libgmp10', 'libgnome',
    'libgnomecanvas', 'libgnomekbd', 'libgnomeui', 'libgnutls30',
    'libgoa', 'libgomp1', 'libgpgme', 'libgphoto2-6',
    'libgpm2', 'libgps', 'libgrantlee', 'libgrilo',
    'libgs9', 'libgsf', 'libgsl', 'libgsoap',
    'libgssapi3', 'libgssdp', 'libgstreamer', 'libgtk2.0',
    'libgtkmm', 'libgtksourceview', 'libgtop', 'libgudev-1.0',
    'libguestfs', 'libgupnp', 'libgusb', 'libgweather',
    'libgxps', 'libhandy', 'libharfbuzz-icu', 'libhavege',
    'libhdf4', 'libhdf5-103', 'libheif1', 'libhiredis',
    'libhogweed4', 'libhpmud', 'libhsqldb', 'libhtml',
    'libhttp', 'libhunspell-1.7', 'libhwloc5', 'libhx509',
    'libhyphen', 'libibus', 'libical3', 'libice6',
    'libiconv-hook', 'libid3tag', 'libidl', 'libidn2-0',
    'libieee1284', 'libigdgmm11', 'libijs', 'libilmbase',
    'libimobiledevice', 'libindicator', 'libinotifytools',
    'libinput', 'libio', 'libip4tc', 'libip6tc',
    'libiptcdata', 'libisc', 'libisccc', 'libisccfg',
    'libisl19', 'libisoburn', 'libisofs', 'libitm1',
    'libjack-jackd2', 'libjansson', 'libjavascriptcoregtk',
    'libjbig0', 'libjbig2dec', 'libjpeg8', 'libjs',
    'libjson-c3', 'libjson-glib', 'libjte', 'libk5crypto3',
    'libkadm5clnt', 'libkadm5srv', 'libkdb5', 'libkeyutils1',
    'libklibc', 'libkmlbase', 'libkmldom', 'libkmlengine',
    'libkmod', 'libkpathsea', 'libkrb5-3', 'libkrb5support0',
    'libksba', 'libkscreen', 'libkwin4', 'liblcms2-2',
    'libldap-2.4-2', 'libldb', 'liblilv', 'liblirc',
    'liblist', 'liblivemedia', 'libllvm10', 'libllvm11',
    'libllvm12', 'libllvm13', 'libllvm15', 'liblmdb0',
    'liblo7', 'liblocale', 'liblockfile1', 'liblog4c',
    'liblouis', 'liblqr', 'liblsan0', 'libltc',
    'liblua', 'liblucene++', 'liblvm2cmd', 'liblwres',
    'liblz4-1', 'liblzma5', 'liblzo2-2', 'libm17n',
    'libmad0', 'libmagic1', 'libmagick', 'libmail',
    'libmariadb3', 'libmatroska', 'libmbim', 'libmcrypt',
    'libmd4c', 'libmediaart', 'libmemcached', 'libmhash',
    'libmicrohttpd', 'libmikmod', 'libminiupnpc', 'libmirclient',
    'libmircommon', 'libmircookie', 'libmirprotobuf', 'libmjpegutils',
    'libmm-glib', 'libmms', 'libmnl', 'libmodplug1',
    'libmono', 'libmount1', 'libmp3lame0', 'libmpc3',
    'libmpdec2', 'libmpeg2-4', 'libmpfr4', 'libmpg123-0',
    'libmpx2', 'libmspub', 'libmtdev1', 'libmtp',
    'libmusicbrainz', 'libmutter', 'libmwaw', 'libmysofa',
    'libnatpmp', 'libncurses5', 'libndp', 'libneon27',
    'libnetcdf13', 'libnettle6', 'libnewt', 'libnfnetlink',
    'libnfs', 'libnftnl', 'libnice',
    'libnl-3-200', 'libnl-genl', 'libnl-route', 'libnm0',
    'libnma', 'libnotify4', 'liboauth', 'libodfgen',
    'libofa', 'libopenal1', 'libopencore', 'libopencv-core',
    'libopenexr', 'libopenjp2-7', 'libopenmpt0',
    'libpackagekit', 'libpam0g', 'libpango-1.0-0',
    'libpangocairo-1.0-0', 'libpangoft2-1.0-0',
    'libpangox-1.0-0', 'libpangoxft-1.0-0',
    'libparpack2', 'libparted', 'libpathplan',
    'libpcap0.8', 'libpci3', 'libpcre3',
    'libpcsclite', 'libperl', 'libpgm-5.2-0', 'libphonon',
    'libpipeline1', 'libpixman-1-0', 'libpkcs11', 'libplist',
    'libplymouth', 'libpng16-16', 'libpocketsphinx',
    'libpolkit', 'libpoppler-glib', 'libpoppler-qt5',
    'libpopt0', 'libportaudio2', 'libpostproc',
    'libpq5', 'libprocps', 'libprotobuf-c',
    'libprotobuf17', 'libproxy1v5',
    'libpthread-stubs0-dev', 'libpulse-mainloop',
    'libpulsedsp', 'libpwquality', 'libpython2.7',
    'libpython3.8', 'libpython3.9', 'libpython3.11',
    'libqca-qt5', 'libqmi', 'libqpdf21', 'libqqwing',
    'libqt5concurrent', 'libqt5core5a', 'libqt5dbus5',
    'libqt5designer', 'libqt5gui5', 'libqt5help5',
    'libqt5network5', 'libqt5opengl5', 'libqt5printsupport',
    'libqt5sql5', 'libqt5svg5', 'libqt5test5',
    'libqt5widgets5', 'libqt5xml5', 'libqt5x11extras',
    'libqtcore4', 'libqtgui4', 'libquadmath0',
    'librabbitmq', 'librados2', 'libraw1394',
    'librbd1', 'libreoffice', 'librelp', 'libresid',
    'librest', 'librevenge', 'librhash0', 'libroken18',
    'librtmp1', 'libsane',
    'libsbig', 'libschroedinger', 'libseccomp2', 'libsecret',
    'libsemanage', 'libsensors5',
    'libserd-0-0', 'libsgutils2',
    'libshout3', 'libsidplay', 'libsigc++',
    'libsignon', 'libslang2', 'libsm6', 'libsmbclient',
    'libsmbios', 'libsnappy1v5',
    'libsnmp', 'libsocket6', 'libsodium23',
    'libsord-0-0', 'libsoundtouch', 'libsoup2.4',
    'libsoxr', 'libspandsp', 'libspatialite',
    'libspeex1', 'libspeexdsp', 'libsphinxbase',
    'libsqlite0', 'libsrtp2',
    'libss2', 'libssh2-1', 'libssl1.0.0',
    'libssl1.1', 'libstartup-notification',
    'libstemmer', 'libstoken',
    'libsubunit', 'libsuitesparseconfig5',
    'libsvga1', 'libsynctex', 'libsysfs',
    'libt3config', 'libt3highlight', 'libt3window',
    'libtag1v5', 'libtalloc2',
    'libtcl', 'libteamdctl',
    'libtext', 'libtidy',
    'libtie', 'libtiff5', 'libtimedate',
    'libtinfo5', 'libtk', 'libtree',
    'libtxc', 'libubsan1',
    'libudev1', 'libudisks2', 'libunbound',
    'libunistring2', 'libunity',
    'libupower', 'libusb-0.1',
    'libusb-1.0-0', 'libusbmuxd', 'libutempter',
    'libuuid1', 'libvisio',
    'libvisual-0.4-0', 'libvncclient1',
    'libvoikko', 'libvorbis0a',
    'libvte-2.91', 'libwavpack1', 'libwayland-bin',
    'libwbclient0', 'libwebkit2gtk',
    'libwebpdemux2', 'libwebrtc',
    'libwind0-heimdal', 'libwmf',
    'libwnck', 'libwoff', 'libwpd', 'libwpg',
    'libwps', 'libwww',
    'libxapian30', 'libxaw7',
    'libxcb-composite0', 'libxcb-damage0',
    'libxcb-doc', 'libxcb-dpms0',
    'libxcb-dri2-0', 'libxcb-dri3-0', 'libxcb-ewmh2',
    'libxcb-glx0', 'libxcb-icccm4', 'libxcb-image0',
    'libxcb-present0', 'libxcb-record0',
    'libxcb-res0', 'libxcb-screensaver0',
    'libxcb-sync1', 'libxcb-xf86dri0',
    'libxcb-xtest0', 'libxcb-xv0',
    'libxerces-c3.2', 'libxfont2',
    'libxklavier', 'libxml++',
    'libxvidcore4', 'libxtables12',
    'libyajl2', 'libyaml-0-2',
    'libyelp', 'libzbar0', 'libzephyr',
    'libzip4', 'libzmq5',
]

print("最终完整系统库识别测试:")
print("=" * 70)

unknown = []
for pkg in test_packages:
    reason = conda.analyze_failure_reason(pkg, "")
    if "系统库/开发包" not in reason:
        unknown.append((pkg, reason))

print(f"\n总计测试: {len(test_packages)} 个包")
print(f"正确识别: {len(test_packages) - len(unknown)} 个")
print(f"未能识别: {len(unknown)} 个")

if unknown:
    print("\n未能识别的包 (前30个):")
    for pkg, reason in unknown[:30]:
        print(f"  {pkg:<45} -> {reason}")
    if len(unknown) > 30:
        print(f"  ... 还有 {len(unknown) - 30} 个")
else:
    print("\n✅ 所有测试包都被正确识别为系统库/开发包！")
    print("当前系统库识别列表已非常完整！")
